---
- name: Check Disk Space Usage
  hosts: 192.168.122.67
  tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space
